version: "3.3"
services:
  pagerduty-checker:
    environment:
      - API_KEY=""
      - HOME_ASSISTANT_URL=""
      - SLEEP_TIME=45
    container_name: pagerduty-checker
    restart: unless-stopped
    image: ghcr.io/cichy1173/pagerduty_checker:latest